### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by MichaelHeil** [merkle-open/aem-generic-multifield#50]
Include release notes for Cloud Version including breaking changes hint

- "namics/generic.." -> "merkle/generic..."
- delete "/apps/namics/genericmultifield" from Crx

**Comment by rdb987** [comment]
Hello.
Do you have an indication of when the cloud compatible version of the generic multifield will be available?
As far as I see the AEMaaCS/master branch is the same as 6.5/master but I see there are new changes in the DEV branch.

**Comment by MichaelHeil** [comment]
Hi @rdb987, 
you are absolutely correct on your analysis of the individual state of the branches.
The volunteers who are currently working on it are not committed to a specific timeline.
But i believe that a rather accurate guesstimation would be that a new version should drop within the next 4 weeks.

Any specific reason you are asking? Are you on a schedule and require assistance?

**Comment by rdb987** [comment]
Hello @MichaelHeil , 

Thanks for your answer. We don't have a tight schedule currently but of course the sooner is available the better is for us. 
We are currently using 6.5 still but our intention is to move to the cloud and therefore we want to build everything already cloud compatible. Maybe for now we simply use the 3.1 version and switch it to the cloud compatible one once is ready.

Best.
